apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portal
  namespace: argocd
spec:
  project: default
  source:
    path: projects/portal/manifests/base
    repoURL: https://github.com/sguldemond/homelab
    targetRevision: HEAD
  destination:
    namespace: my-portal
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
