site_name: stan syfert
theme:
  name: terminal
  features:
      - navigation.side.indexes
nav:
  - home: index.md
  - blog:
    - Index: blog/index.md
    - goblin operator: blog/goblin-operator.md
    - my homelab: blog/my-homelab.md
    - this blog: blog/this-blog.md
  - homelab: homelab.md
  - journal: journal.md
