site_name: stan syfert
theme:
  name: terminal
  features:
      - navigation.side.indexes
nav:
  - blog:
    - Index: blog/index.md
    - this blog: blog/this-blog.md
  - homelab: index.md
  - journal: journal.md
