- name: Configure L2 bridge on Debian 13
  hosts: homelab-machines
  become: true
  vars:
    interfaces_path: /etc/network/interfaces
  pre_tasks:
    - name: Ensure ifupdown2 is present (better for bridges on Debian 13)
      ansible.builtin.apt:
        name: ifupdown2
        state: present
        update_cache: true

  tasks:
    - name: Template /etc/network/interfaces
      ansible.builtin.template:
        src: vars/interfaces.j2
        dest: "{{ interfaces_path }}"
        mode: "0644"
      notify: Apply networking

  handlers:
    - name: Apply networking
      ansible.builtin.shell: |
        ifdown br0 || true
        ifup br0
      listen: Apply networking
