apiVersion: v1
kind: Service
metadata:
  name: go-echo-service
  namespace: default
  annotations:
    metallb.universe.tf/address-pool: egress-pool
  labels:
    app: tcp-echo
    system: example
spec:
  externalTrafficPolicy: Local
  selector:
    app: tcp-echo
  ports:
    - name: tcp
      protocol: TCP
      port: 2701
      targetPort: 2701
    - name: udp
      protocol: UDP
      port: 2701
      targetPort: 2701
  type: LoadBalancer
