apiVersion: k8s.ovn.org/v1
kind: EgressService
metadata:
  name: go-echo-service  # must match the Service name
  namespace: default
spec:
  sourceIPBy: LoadBalancerIP
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker: worker
