---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  namespace: my-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      serviceAccountName: portal-readonly
      containers:
        - name: my-portal
          image: registry.macmini.home/my-portal:latest
          ports:
            - containerPort: 4173
---
apiVersion: v1
kind: Service
metadata:
  name: portal-svc
  namespace: my-portal
spec:
  ports:
    - port: 4173
      targetPort: 4173
  selector:
    app: portal
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portal-ingress
  namespace: my-portal
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: portal.macmini.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portal-svc
                port:
                  number: 4173
---
apiVersion: v1
kind: Service
metadata:
  name: portal-svc-public
  namespace: my-portal
spec:
  ports:
    - port: 80
      targetPort: 4173
  selector:
    app: portal
---
