---
apiVersion: v1
kind: Namespace
metadata:
  name: whoami
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-svc
  namespace: whoami
  labels:
    service: whoami
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    app: whoami
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-ingress
  namespace: whoami
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: whoami.talos.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami-svc
                port:
                  number: 80
---
# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: whoami
#   namespace: whoami
# spec:
#   entryPoints:
#     - web
#   routes:
#     - match: Host(`whoami.talos.home`)
#       kind: Rule
#       services:
#         - name: whoami-svc
#           port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deploy
  namespace: whoami
  labels:
    app: whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami:v1.8.0
          ports:
            - name: whoami
              containerPort: 80
