# jenkins-buildx-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: buildx-manager
  namespace: jenkins           # <-- your Jenkins namespace
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "pods/log", "services", "configmaps", "deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: buildx-manager-binding
  namespace: jenkins
subjects:
  - kind: ServiceAccount
    name: jenkins               # <-- your Jenkins controller/agent SA
    namespace: jenkins
roleRef:
  kind: Role
  name: buildx-manager
  apiGroup: rbac.authorization.k8s.io
