allow_k8s_contexts('macmini')
docker_build(
    'registry.macmini.home/my-portal:latest',
    context='.',
    only=['my-portal'],
)

k8s_yaml('manifests/portal.yaml')

k8s_resource('portal', port_forwards=4173)
