name: build-publish-and-bump

on:
  push:
    branches: [develop, main, 'release/**']
    paths:
      - 'projects/portal/my-portal/**'
      - 'projects/portal/Dockerfile'
  pull_request:
    branches: [develop, main, 'release/**']
    paths:
      - 'projects/portal/my-portal/**'
      - 'projects/portal/Dockerfile'
  workflow_dispatch:

env:
  IMAGE_NAME: sguldemond/my-portal
  INFRA_REPO: sguldemond/homelab
  KUS_PATH: projects/portal/manifests/base

jobs:
  build-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      packages: read

    steps:
      - name: Checkout portal
        uses: actions/checkout@v4

      - name: Set vars
        id: vars
        run: |
          SHA=$(git rev-parse --short HEAD)
          echo "sha=$SHA" >> $GITHUB_OUTPUT


      - name: Log in to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: type=raw,value=${{ steps.vars.outputs.sha }}

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: buildpush
        uses: docker/build-push-action@v6
        with:
          context: projects/portal
          file: projects/portal/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:cache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:cache,mode=max
          outputs: type=image,name=${{ env.IMAGE_NAME }},push=true

      - name: Patch image tag with Kustomize
        run: |
          set -euo pipefail
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/
          cd "${{ env.KUS_PATH }}"
          kustomize edit set image "${{ env.IMAGE_NAME }}=${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha }}"
          
      - name: Commit & push bump
        run: |
          git config user.name  "ci-bot"
          git config user.email "ci-bot@users.noreply.github.com"
          git add "${{ env.KUS_PATH }}/kustomization.yaml"
          git commit -m "portal: bump image to ${{ steps.vars.outputs.sha }}" || echo "No changes to commit"
          git push origin "${GITHUB_REF_NAME}"
